[package]
name = "run_in_wsl_server"
version = "0.1.0"
authors = ["Diego Magdaleno <Diego Magdaleno>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "3.0.1"
regex = "1"